#page title
page_title                                : # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120
ios_app_country                           : us

appstore_link                             : # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : # Enter Google Play Store URL.
presskit_download_link                    : # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Write a short tagline for your app.

enable_smart_app_banner                   : true # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Trent Morris
business_name                             : Atomic Software
your_link                                 : https://trentmorris.com
your_city                                 : Las Vegas, USA
email_address                             : hello@atomic.software
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : trentjmorris
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : magic
    
  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : mobile

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : play-circle

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : sync

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : star

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : link

  - title                                 : Feature
    description                           : Feature Description
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

header_gradient_color_a                   : hsl(289, 64%, 65%)      # header gradient start color
header_gradient_color_b                   : hsl(179, 80%, 44%)      # header gradient end color

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


# App-specific Privacy Policy passages

privacy__last_updated                     : February 3, 2023
privacy_1_1__info_we_collect              : 

  # - This is the first sample passage

privacy_4_0__subcontractors               :

  - name                                  : Apple Inc
    country                               : USA
    description                           : Software distribution, marketing, and payment processing

  - name                                  : Digital Ocean
    country                               : USA
    description                           : Server hosting, remote computing

  - name                                  : RevenueCat
    country                               : USA
    description                           : Subscription and In-App-Purchase management

  - name                                  : Mailchimp
    country                               : USA
    description                           : Customer communication, support, and newsletter distribution

  # - name                                  : Digital Ocean
  #   country                               : USA
  #   description                           : Server hosting, remote computing

terms__last_updated                     : February 3, 2023











####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
